In [ ]:
import pandas as pd
data = pd.read_csv("/content/archive (4).zip")
print(data.head())

   Index                   Title             Artist            Top Genre  \
0      1                 Sunrise        Norah Jones      adult standards
1      2             Black Night        Deep Purple           album rock
2      3          Clint Eastwood           Gorillaz  alternative hip hop
3      4           The Pretender       Foo Fighters    alternative metal
4      5  Waitin' On A Sunny Day  Bruce Springsteen         classic rock

   Year  Beats Per Minute (BPM)  Energy  Danceability  Loudness (dB)  \
0  2004                     157      30            53            -14
1  2000                     135      79            50            -11
2  2001                     168      69            66             -9
3  2007                     173      96            43             -4
4  2002                     106      82            58             -5

   Liveness  Valence Length (Duration)  Acousticness  Speechiness  Popularity
0        11       68               201            94            3          71
1        17       81               207            17            7          39
2         7       52               341             2           17          69
3         3       37               269             0            4          76
4        10       87               256             1            3          59

In [ ]:
data

,Index,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,2,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,4,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,1990,Heartbreak Hotel,Elvis Presley,adult standards,1958,94,21,70,-12,11,72,128,84,7,63
1990,1991,Hound Dog,Elvis Presley,adult standards,1958,175,76,36,-8,76,95,136,73,6,69
1991,1992,Johnny B. Goode,Chuck Berry,blues rock,1959,168,80,53,-9,31,97,162,74,7,74
1992,1993,Take Five,The Dave Brubeck Quartet,bebop,1959,174,26,45,-13,7,60,324,54,4,65
1993,1994,Blueberry Hill,Fats Domino,adult standards,1959,133,50,49,-10,16,83,148,74,3,56

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data = data.drop(columns='Index')

In [ ]:
data

,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76
4,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,Heartbreak Hotel,Elvis Presley,adult standards,1958,94,21,70,-12,11,72,128,84,7,63
1990,Hound Dog,Elvis Presley,adult standards,1958,175,76,36,-8,76,95,136,73,6,69
1991,Johnny B. Goode,Chuck Berry,blues rock,1959,168,80,53,-9,31,97,162,74,7,74
1992,Take Five,The Dave Brubeck Quartet,bebop,1959,174,26,45,-13,7,60,324,54,4,65
1993,Blueberry Hill,Fats Domino,adult standards,1959,133,50,49,-10,16,83,148,74,3,56

In [ ]:
data2 = data[["Beats Per Minute (BPM)", "Loudness (dB)",
              "Liveness", "Valence", "Acousticness",
              "Speechiness"]]

from sklearn.preprocessing import MinMaxScaler
for i in data.columns:
    MinMaxScaler(i)

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10)
clusters = kmeans.fit_predict(data2)

In [ ]:
data["Music Segments"] = clusters
MinMaxScaler(data["Music Segments"])
data["Music Segments"] = data["Music Segments"].map({1: "Cluster 1", 2:
    "Cluster 2", 3: "Cluster 3", 4: "Cluster 4", 5: "Cluster 5",
    6: "Cluster 6", 7: "Cluster 7", 8: "Cluster 8",
    9: "Cluster 9", 10: "Cluster 10"})

In [ ]:
print(data.head())

                    Title             Artist            Top Genre  Year  \
0                 Sunrise        Norah Jones      adult standards  2004
1             Black Night        Deep Purple           album rock  2000
2          Clint Eastwood           Gorillaz  alternative hip hop  2001
3           The Pretender       Foo Fighters    alternative metal  2007
4  Waitin' On A Sunny Day  Bruce Springsteen         classic rock  2002

   Beats Per Minute (BPM)  Energy  Danceability  Loudness (dB)  Liveness  \
0                     157      30            53            -14        11
1                     135      79            50            -11        17
2                     168      69            66             -9         7
3                     173      96            43             -4         3
4                     106      82            58             -5        10

   Valence Length (Duration)  Acousticness  Speechiness  Popularity  \
0       68               201            94            3          71
1       81               207            17            7          39
2       52               341             2           17          69
3       37               269             0            4          76
4       87               256             1            3          59

  Music Segments
0      Cluster 5
1            NaN
2      Cluster 8
3      Cluster 8
4      Cluster 7

In [ ]:
import plotly.graph_objects as go
PLOT = go.Figure()
for i in list(data["Music Segments"].unique()):


    PLOT.add_trace(go.Scatter3d(x = data[data["Music Segments"]== i]['Beats Per Minute (BPM)'],
                                y = data[data["Music Segments"] == i]['Energy'],
                                z = data[data["Music Segments"] == i]['Danceability'],
                                mode = 'markers',marker_size = 6, marker_line_width = 1,
                                name = str(i)))
PLOT.update_traces(hovertemplate='Beats Per Minute (BPM): %{x} <br>Energy: %{y} <br>Danceability: %{z}')


PLOT.update_layout(width = 800, height = 800, autosize = True, showlegend = True,
                   scene = dict(xaxis=dict(title = 'Beats Per Minute (BPM)', titlefont_color = 'black'),
                                yaxis=dict(title = 'Energy', titlefont_color = 'black'),
                                zaxis=dict(title = 'Danceability', titlefont_color = 'black')),
                   font = dict(family = "Gilroy", color  = 'black', size = 12))

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Music features
features = [
    "Beats Per Minute (BPM)",
    "Loudness (dB)",
    "Liveness",
    "Valence",
    "Acousticness",
    "Speechiness"
]

# Select features
X = data[features]

# Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Find best cluster score
best_score = -1
best_k = 0

for k in range(2, 11):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_scaled)

    score = silhouette_score(X_scaled, labels)

    print(f"K = {k} | Silhouette Score = {score:.4f}")

    if score > best_score:
        best_score = score
        best_k = k

print("\nBest K =", best_k)
print("Best Silhouette Score =", round(best_score, 4))

K = 2 | Silhouette Score = 0.3200
K = 3 | Silhouette Score = 0.2702
K = 4 | Silhouette Score = 0.2838
K = 5 | Silhouette Score = 0.2599
K = 6 | Silhouette Score = 0.2266
K = 7 | Silhouette Score = 0.2128
K = 8 | Silhouette Score = 0.1932
K = 9 | Silhouette Score = 0.1881
K = 10 | Silhouette Score = 0.1892

Best K = 2
Best Silhouette Score = 0.32

In [ ]:
import joblib

joblib.dump(kmeans, "kmeans_model.joblib")
joblib.dump(scaler, "scaler.joblib")

print("Model and Scaler saved successfully!")

Model and Scaler saved successfully!

In [ ]:
import joblib

kmeans = joblib.load("kmeans_model.joblib")
scaler = joblib.load("scaler.joblib")